### ISSUE TITLE
OSError: exception: access violation reading 0x000002ABA0141000

### ISSUE THREAD

**Issue by abdjiber** [microsoft/interpret#25] opened 2019-06-11 22:14 UTC
Hi dear InterpretML Team, 

I'm having this issue: OSError: exception: access violation reading 0x000002ABA0141000. This issue is with n_jobs=-1, when I set n_jobs=1 I got the same issue but access violation reading 0x0000026108C46000. I have no idea how to fix it. Seems that it comes from joblib! Here is what I'm trying to do on Jupyter notebook:

ebm = ExplainableBoostingClassifier(n_jobs=-1)
ebm.fit(x_train, y_train)
preds_interpret = ebm.predict_proba(x_test)

And here the traceback:

Traceback (most recent call last):
  File "C:\anaconda\lib\site-packages\joblib\externals\loky\process_executor.py", line 418, in _process_worker
    r = call_item()
  File "C:\anaconda\lib\site-packages\joblib\externals\loky\process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\anaconda\lib\site-packages\joblib\_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "C:\anaconda\lib\site-packages\joblib\parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "C:\anaconda\lib\site-packages\joblib\parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\anaconda\lib\site-packages\interpret\glassbox\ebm\ebm.py", line 789, in train_model
    return estimator.fit(X, y)
  File "C:\anaconda\lib\site-packages\interpret\glassbox\ebm\ebm.py", line 386, in fit
    validation_scores=None,
  File "C:\anaconda\lib\site-packages\interpret\glassbox\ebm\internal.py", line 376, in __init__
    self._initialize_training_classification()
  File "C:\anaconda\lib\site-packages\interpret\glassbox\ebm\internal.py", line 461, in _initialize_training_classification
    self.num_inner_bags,
OSError: exception: access violation reading 0x000002ABA0141000

**Comment by interpret-ml** [comment] 2019-06-14 23:24
Hi @abdjiber,

Thanks for taking the time to report this! We've been looking into this issue, and just added new logging/debugging functionality in v0.1.9 that might help us diagnose and fix the error. 

Once you've upgraded to interpret v0.1.9:
`pip install -U interpret`

Would you mind running this code at the start of your script/notebook?
```python
from interpret.develop import debug_mode

debug_mode(log_filename='log.txt', log_level='INFO', native_debug=True)
```

If you run EBM afterwards, with `n_jobs=1`, interpret will produce a a log.txt file -- it would be great if you could send the file to us! You can comment it here on github, provide us a link, or send it to us privately at interpret@microsoft.com. 

Thanks, 
-InterpretML Team

**Comment by interpret-ml** [comment] 2019-06-28 20:42
Hi @abdjiber,
 
Thanks for sending us that log file.  We were able to track down this issue thanks to your help!
 
The issue is that we currently don't support multiclass prediction.  Instead of throwing a nice exception indicating this though, our package crashes instead.  We're going to add an exception at the entry point so that this won't confuse any future users who try multiclass.
 
Multiclass prediction is one of our highest priority feature additions at the moment, and we’re actively working towards getting it in.  Most of the functionality is actually already in the package, but not exposed yet since it isn't ready.
 
I'm closing this bug for now since we've identified the problem, and will shortly change the package to not crash this way anymore.  I'll post here again though once we've added multiclass prediction so that you can re-try it on your data if you’re still interested at that time.  In the meantime, most likely you could gain some insights into your data fairly easily by using One-vs.-rest ( https://en.wikipedia.org/wiki/Multiclass_classification ).
 
-InterpretML Team

**Closed by interpret-ml** 2019-06-28 20:42 UTC
Labels: bug

**Comment by abdjiber** [comment] 2019-08-26 21:55
Hi,

This gonna be amazing! Thanks for the information.

Regards

Le lun. 26 août 2019 à 21:38, interpret-ml <notifications@github.com> a
écrit :
